name: deploy react app
on: push
permissions:
  contents: write
jobs:
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4
        
      - name: npm install
        run: npm install
        
      - name: npm run build
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build
        
      - name: npm run test
        run: npm run test -- --passWithNoTests

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
