name: Deploy React App
on:
  push:
    branches:
      - main  # Change this to the default branch of your repo if it's not 'main'
      
permissions:
  contents: write

jobs:
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone the repository
      - name: Clone the repository
        uses: actions/checkout@v4
        
      # Step 2: Install npm dependencies
      - name: Install npm packages
        run: npm install
        
      # Step 3: Build the app
      - name: Build the app
        run: npm run build
        
      # Step 4: Run npm tests (optional, can be removed if you don't want to test on deploy)
      - name: Run npm tests
        run: npm run test -- --coverage --watchAll=false

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build in gh-deploy.yml
