name: Deployment Pg
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing NPM packages
        run: npm install

      - name: Building project
        run: |
          npm run build || { echo "Build failed"; exit 1; }

      - name: Running tests
        run: npm run test

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v4.4.3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Downloading artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production-files
          path: ./build

      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Set up Git for commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Commit changes to Deployment Pg
        run: |
          git add -A
          git commit -m "Deploying new build to GitHub Pages"
          git push origin gh-pages
